# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'quickCluster' do
pod 'SwiftyJSON', '~> 2.2.0'
end

target 'quickClusterTests' do

end

